### ISSUE TITLE
How to Revert [ Geforce-Kepler-patcher ] Changes Manually

### ISSUE THREAD

**Issue by Jumbo810** [chris1111/OpenCore-Creator#2]
Bro i Installed Geforce-Kepler-patcher in Sonoma and i can't boot into my Sonoma Hackintosh. So can u guide me how can i revert these changes manually by deleting those patches and i can access my Hackintosh disk through windows So it will be easy

**Comment by Jumbo810** [comment]
i know it's not a place this issue but that's issues only a way to contact you

**Comment by chris1111** [comment]
There is no way, Geforce-Kepler-patcher is not for Sonoma! You have screwup your sonoma disk.
Geforce-Kepler-patcher is ARCHIVED so there is no support for the app; please dont ask for support.
